project_name: shcopy
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    - go mod tidy
    - rm -rf manpages
    - mkdir manpages
    - sh -c 'go run . --man | gzip -c >./manpages/{{ .ProjectName }}.1.gz'
builds:
  -
    ldflags: -s -w -X main.ProjectName={{ .ProjectName }} -X main.Version=v{{ .Version }} -X main.CommitSHA={{ .ShortCommit }}
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
      - netbsd
    goarch:
      - amd64
      - arm64
      - "386"
      - arm
    goarm:
      - "7"
      - "6"
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarm: "7"
      - goos: windows
        goarm: "6"

archives:
  -
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      windows: Windows
      darwin: Darwin
      386: i386
      amd64: x86_64
    files:
      - README*
      - LICENSE*
      - manpages/*

nfpms:
  -
    vendor: aymanbagabas
    homepage: "https://github.com/aymanbagabas/shcopy"
    maintainer: "Ayman Bagabas <ayman.bagabas@gmail.com>"
    description: "Copy text to clipboard from anywhere using ANSI OSC 52 sequence"
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: ./manpages/{{ .ProjectName }}.1.gz
        dst: /usr/share/man/man1/{{ .ProjectName }}.1.gz

brews:
  - tap:
      owner: 'aymanbagabas'
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: 'Ayman Bagabas'
      email: 'ayman.bagabas@gmail.com'
    homepage: 'https://github.com/aymanbagabas/shcopy'
    description: 'Copy text to clipboard from anywhere using ANSI OSC 52 sequence'
    install: |-
      bin.install "{{ .ProjectName }}"
      man1.install "manpages/{{ .ProjectName }}.1.gz"


aurs:
  - maintainers: ['Ayman Bagabas <ayman.bagabas@gmail.com>']
    description: 'Copy text to clipboard from anywhere using ANSI OSC 52 sequence'
    name: '{{ .ProjectName }}-bin'
    homepage: 'https://github.com/aymanbagabas/shcopy'
    license: MIT
    private_key: '{{ .Env.AUR_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/{{ .ProjectName }}-bin.git'
    package: |-
      # bin
      install -Dm755 "./{{ .ProjectName }}" "${pkgdir}/usr/bin/{{ .ProjectName }}"
      # license
      mkdir -p "${pkgdir}/usr/share/licenses/{{ .ProjectName }}/"
      install -Dm644 ./LICENSE* "${pkgdir}/usr/share/licenses/{{ .ProjectName }}/"
      # man pages
      install -Dm644 "./manpages/{{ .ProjectName }}.1.gz" "${pkgdir}/usr/share/man/man1/{{ .ProjectName }}.1.gz"

checksum:
  name_template: 'checksums.txt'

source:
  enabled: true

snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
