# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json

version: 2

project_name: shcopy
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    - go mod tidy
    - rm -rf manpages
    - mkdir manpages
    - sh -c 'go run . --man | gzip -c >./manpages/{{ .ProjectName }}.1.gz'
builds:
  - ldflags: -s -w -X main.ProjectName={{ .ProjectName }} -X main.Version=v{{ .Version }} -X main.CommitSHA={{ .ShortCommit }}
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
      - netbsd
    goarch:
      - amd64
      - arm64
      - "386"
      - arm
      - ppc64le
      - riscv64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarm: "7"

archives:
  - format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- with .Arm}}v{{ . }}{{ end }}
    files:
      - README*
      - LICENSE*
      - manpages/*

nix:
  - repository:
      owner: aymanbagabas
      name: nur
    homepage: "https://github.com/aymanbagabas/{{ .ProjectName }}"
    description: "Copy text to clipboard from anywhere using ANSI OSC 52 sequence"
    license: mit

nfpms:
  - vendor: aymanbagabas
    homepage: "https://github.com/aymanbagabas/shcopy"
    maintainer: "Ayman Bagabas <ayman.bagabas@gmail.com>"
    description: "Copy text to clipboard from anywhere using ANSI OSC 52 sequence"
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: ./manpages/{{ .ProjectName }}.1.gz
        dst: /usr/share/man/man1/{{ .ProjectName }}.1.gz

brews:
  - repository:
      owner: "aymanbagabas"
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: "Ayman Bagabas"
      email: "ayman.bagabas@gmail.com"
    homepage: "https://github.com/aymanbagabas/shcopy"
    description: "Copy text to clipboard from anywhere using ANSI OSC 52 sequence"
    install: |-
      bin.install "{{ .ProjectName }}"
      man1.install "manpages/{{ .ProjectName }}.1.gz"

aurs:
  - maintainers: ["Ayman Bagabas <ayman.bagabas@gmail.com>"]
    description: "Copy text to clipboard from anywhere using ANSI OSC 52 sequence"
    name: "{{ .ProjectName }}-bin"
    homepage: "https://github.com/aymanbagabas/shcopy"
    license: MIT
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/{{ .ProjectName }}-bin.git"
    package: |-
      # bin
      install -Dm755 "./{{ .ProjectName }}" "${pkgdir}/usr/bin/{{ .ProjectName }}"
      # license
      mkdir -p "${pkgdir}/usr/share/licenses/{{ .ProjectName }}/"
      install -Dm644 ./LICENSE* "${pkgdir}/usr/share/licenses/{{ .ProjectName }}/"
      # man pages
      install -Dm644 "./manpages/{{ .ProjectName }}.1.gz" "${pkgdir}/usr/share/man/man1/{{ .ProjectName }}.1.gz"

scoops:
  - repository:
      owner: aymanbagabas
      name: scoop-bucket
      token: "{{ .Env.SCOOP_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: "Ayman Bagabas"
      email: "ayman.bagabas@gmail.com"
    homepage: "https://github.com/aymanbagabas/shcopy"
    description: "Copy text to clipboard from anywhere using ANSI OSC 52 sequence"
    license: MIT

checksum:
  name_template: "checksums.txt"

source:
  enabled: true

snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
